include( ${JSD_CMAKE_SETTINGS_PATH}/set-verbosity-configuration.cmake )

JSD_CMAKE_CURRENT_FILE_IN( "set-linux-linker-settings.cmake" )

if ( UNIX )
	set( JSD_CMAKE_CXX_FLAGS "" )
	set( JSD_CMAKE_CXX_FLAGS_DEBUG "" )
	set( JSD_CMAKE_CXX_FLAGS_RELEASE "" )

	set( JSD_CMAKE_SHARED_LINKER_FLAGS "" )
	set( JSD_CMAKE_EXE_LINKER_FLAGS "" )

	#QMAKE_LFLAGS_RELEASE -= -Wl,-O1
	#QMAKE_LFLAGS_RELEASE -= -Wl,-O2
	#QMAKE_LFLAGS_RELEASE += -Wl,-O3

	string( REPLACE ";" " " JSD_CMAKE_LINKER_FLAGS_STR "${JSD_CMAKE_LINKER_FLAGS}" )
	string( REPLACE ";" " " JSD_CMAKE_LINKER_FLAGS_DEBUG_STR "${JSD_CMAKE_LINKER_FLAGS_DEBUG}" )
	string( REPLACE ";" " " JSD_CMAKE_LINKER_FLAGS_RELEASE_STR "${JSD_CMAKE_LINKER_FLAGS_RELEASE}" )
	string( REPLACE ";" " " JSD_CMAKE_SHARED_LINKER_FLAGS_STR "${JSD_CMAKE_SHARED_LINKER_FLAGS}" )
	string( REPLACE ";" " " JSD_CMAKE_EXE_LINKER_FLAGS_STR "${JSD_CMAKE_EXE_LINKER_FLAGS}" )

	set( CMAKE_SHARED_LINKER_FLAGS "" )
	set( CMAKE_SHARED_LINKER_FLAGS_DEBUG "" )
	set( CMAKE_SHARED_LINKER_FLAGS_RELEASE "" )
	set( CMAKE_EXE_LINKER_FLAGS "" )
	set( CMAKE_EXE_LINKER_FLAGS_DEBUG "" )
	set( CMAKE_EXE_LINKER_FLAGS_RELEASE "" )

	set( JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS "" )
	list( APPEND JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS "-Wl,--no-undefined" )
	list( APPEND JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS "-Wl,--unresolved-symbols=report-all" ) # ignore-in-object-files
##	list( APPEND JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS "-Wl,--no-allow-shlib-undefined" )
	list( APPEND JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS "-z defs" )

	string( REPLACE ";" " " JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS_STR "${JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS}" )

	if ( JSD_CMAKE_DEBUG )
		set( CMAKE_SHARED_LINKER_FLAGS "${JSD_CMAKE_LINKER_FLAGS_STR} ${JSD_CMAKE_LINKER_FLAGS_DEBUG_STR} ${JSD_CMAKE_SHARED_LINKER_FLAGS_STR} ${JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS_STR}" )
		set( CMAKE_EXE_LINKER_FLAGS "${JSD_CMAKE_LINKER_FLAGS_STR} ${JSD_CMAKE_LINKER_FLAGS_DEBUG_STR} ${JSD_CMAKE_EXE_LINKER_FLAGS_STR}" )

	elseif ( JSD_CMAKE_RELEASE )
		set( CMAKE_SHARED_LINKER_FLAGS "${JSD_CMAKE_LINKER_FLAGS_STR} ${JSD_CMAKE_LINKER_FLAGS_RELEASE_STR} ${JSD_CMAKE_SHARED_LINKER_FLAGS_STR} ${JSD_ADDITIONAL_MAKE_SHARED_LINKER_FLAGS_STR}" )
		set( CMAKE_EXE_LINKER_FLAGS "${JSD_CMAKE_LINKER_FLAGS_STR} ${JSD_CMAKE_LINKER_FLAGS_RELEASE_STR} ${JSD_CMAKE_EXE_LINKER_FLAGS_STR}" )

	else()
		message( SEND_ERROR "[JSD] WINDOWS LINKER SETTINGS: linux-linker-settings.cmake: neither release nor debug" )

	endif()

#	message( STATUS "[JSD] CMAKE_SHARED_LINKER_FLAGS: ${CMAKE_SHARED_LINKER_FLAGS}" )

else()
	message( SEND_ERROR "[JSD] LINUX LINKER SETTINGS: linux-linker-settings.cmake is included while not on linux" )

endif()

JSD_CMAKE_CURRENT_FILE_OUT( "linux-linker-settings.cmake" )
