set( ${PROJECT_NAME}_DEPENDENCY_DIRS ${${PROJECT_NAME}_DEPENDENCY_DIRS_VAR} CACHE INTERNAL "[JSD] ${PROJECT_NAME}_DEPENDENCY_DIRS" FORCE )
set( ${PROJECT_NAME}_DEPENDENCY_LIBS ${${PROJECT_NAME}_DEPENDENCY_LIBS_VAR} CACHE INTERNAL "[JSD] ${PROJECT_NAME}_DEPENDENCY_LIBS" FORCE )
set( ${PROJECT_NAME}_BUILD_DEFINITIONS ${${PROJECT_NAME}_BUILD_DEFINITIONS_VAR} CACHE INTERNAL "[JSD] ${PROJECT_NAME}_DEFINITIONS" FORCE )
set( ${PROJECT_NAME}_LINK_DEFINITIONS ${${PROJECT_NAME}_LINK_DEFINITIONS_VAR} CACHE INTERNAL "[JSD] ${PROJECT_NAME}_DEFINITIONS" FORCE )


JSD_SHOW_PROJECT_DEPENDENCY()
