JSD_CMAKE_CURRENT_FILE_IN( "set-target-directories.cmake" )


set( JSD_DESTINATION_BINARIES_DIR __binaries )
set( JSD_DESTINATION_LIBRARIES_DIR __libraries )

set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JSD_DESTINATION_LIBRARIES_DIR} )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JSD_DESTINATION_LIBRARIES_DIR} )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JSD_DESTINATION_BINARIES_DIR} )


JSD_CMAKE_CURRENT_FILE_OUT( "set-target-directories.cmake" )
